export const JOBS = {
  productManager: "기획자",
  designer: "디자이너",
  developer: "개발자",
} as const;

export const SITUATIONS = {
  codeReview: "내 코드를 비난하는 동료",
  bubbles: "밤새운 기획이 물거품되다",
  nastyClient: "구린 미감의 클라이언트",
  love: "사수의 고백공격",
  passWork: "자신의 업무를 떠넘기는 상사",
} as const;

export const GENDER = {
  male: "남성",
  female: "여성",
} as const;

export const PERSONALITIES = {
  Adaptable: "잘 적응하는",
  Adventurous: "모험심이 강한",
  Affectionate: "다정한",
  Alert: "경계심이 강한",
  Ambitious: "야심만만한",
  Analytical: "분석적인",
  Appreciative: "고마워할 줄 아는",
  Bold: "대범한",
  Calm: "침착한",
  Cautious: "조심성이 많은",
  Centered: "중심이 잡힌",
  Charming: "매력적인",
  Confident: "자신감 있는",
  Cooperative: "협조적인",
  Courageous: "용기 있는",
  Courteous: "예의 바른",
  Creative: "창조적인",
  Curious: "호기심이 많은",
  Decisive: "결단력 있는",
  Diplomatic: "협상에 능한",
  Disciplined: "절제력이 있는",
  Discreet: "신중한",
  Easygoing: "느긋한",
  Efficient: "효율적인",
  Empathetic: "공감을 잘하는",
  Enthusiastic: "열정적인",
  Extroverted: "외향적인",
  Flamboyant: "대담한",
  Friendly: "우호적인",
  Funny: "재미있는",
  Generous: "관대한",
  Gemtle: "온화한",
  Happy: "행복해하는",
  Honest: "정직한",
  Humble: "겸손한",
  Idealistic: "이상주의적인",
  Imaginative: "상상력이 풍부한",
  Independent: "독립적인",
  Industrious: "부지런한",
  Innocent: "순수한",
  Intelligent: "지적인",
  Introverted: "내성적인",
  Just: "정의로운",
  Kind: "친절한",
  Loyal: "충직한",
  Mature: "어른스러운",
  Merciful: "자비로운",
  Meticulous: "꼼꼼한",
  Obedient: "순종적인",
  Objective: "객관적인",
  Observant: "관찰력이 뛰어난",
  Optimistic: "낙천적인",
  Organized: "조직적인",
  Patient: "참을성이 많은",
  Patriotic: "애국적인",
  Pensive: "사색적인",
  Persistent: "끈기 있는",
  Persuasive: "설득력 있는",
  Philosophical: "철학적인",
  Playful: "놀기 좋아하는",
  Proactive: "주도적인",
  Professional: "전문적인",
  Proper: "정확한",
  Protective: "보호본능이 강한",
  Quirky: "별난",
  Resourceful: "지략이 풍부한",
  Responsible: "책임감 있는",
  Sensual: "관능적인",
  Sentimental: "감성이 풍부한",
  Simple: "소박한",
  Sophisticated: "교양 있는",
  Spontaneous: "즉흥적인",
  Studious: "학구적인",
  Supportive: "조력적인",
  Talented: "재능 있는",
  Thrifty: "알뜰한",
  Tolerant: "관용적인",
  Traditional: "보수적인",
  Trusting: "잘 믿는",
  Uninhibited: "자유분방한",
  Unselfish: "사심이 없는",
  Whimsical: "기발한",
  Wholesome: "건전한",
  Wise: "현명한",
  Witty: "재치 있는",
  Addictive: "중독에 빠지는",
  Antisocial: "반사회적인",
  Apathetic: "무관심한",
  Callous: "냉담함",
  Catty: "심술궂음",
  Childish: "어린아이 같은",
  Cocky: "거만한",
  Compulsive: "강박적인",
  Confrontational: "대립을 일삼는",
  Controlling: "지배욕이 강한",
  Cowardly: "비겁한",
  Cruel: "잔인한",
  Cynical: "냉소적인",
  Defensive: "방어적인",
  Devious: "기만적인",
  Dishonest: "정직하지 못한",
  Disloyal: "불충한",
  Disorganized: "체계적이지 못한",
  Disrespectful: "무례한",
  Evasive: "얼버무리며 회피하는",
  Evil: "악독한",
  Fanatical: "광적인",
  Flaky: "엉뚱한",
  Foolish: "어리석은",
  Forgetful: "잘 잊어버리는",
  Frivolous: "경박함",
  Fussy: "깐깐한",
  Gossipy: "남의 말을 하기 좋아하는",
  Greedy: "탐욕스러운",
  Grumpy: "퉁명스러운",
  Gullible: "잘 속는",
  Haughty: "오만한",
  Hostile: "적대적인",
  Humorless: "재미없는",
  Hypocritical: "위선적인",
  Ignorant: "무식한",
  Impulsive: "충동적인",
  Inattentive: "부주의한",
  Indecisive: "우유부단한",
  Inflexible: "융통성이 없는",
  Inhibited: "병적으로 내성적인",
  Insecure: "불안정한",
  Irrational: "비이성적인",
  Irresponsible: "무책임한",
  Jealous: "질투심이 강한",
  Judgmental: "비판적인",
  "Know-It-All": "뭐든 아는 체하는",
  Lazy: "게으른",
  Macho: "마초적인",
  Manipulative: "조종하는",
  Martyr: "희생양인 척하는",
  Materialistic: "물질만능주의인",
  Melodramatic: "감정과잉인",
  Mischievous: "짓궂은",
  Morbid: "병적인",
  Nagging: "잔소리가 심한",
  Needy: "애정결핍인",
  Nervous: "신경과민인",
  Nosy: "오지랖이 넓은",
  Obsessive: "집착이 강한",
  Oversensitive: "과민한",
  Paranoid: "피해망상이 심한",
  Perfectionist: "완벽주의인",
  Pessimistic: "비관적인",
  Possessive: "소유욕이 강한",
  Prejudiced: "편파적인",
  Pretentious: "허세를 부리는",
  Promiscuous: "문란한",
  Pushy: "강압적인",
  Rebellious: "반항적인",
  Reckless: "무모한",
  Resentful: "원망하는",
  Rowdy: "말썽을 피우는",
  Scatterbrained: "산만한",
  "Self-Destructive": "자기파괴적인",
  "Self-Indulgent": "방종하는",
  Selfish: "이기적인",
  Sleazy: "추잡함",
  Spoiled: "응석을 부리는",
  Stingy: "인색한",
  Stubborn: "고집불통인",
  Subservient: "비굴한",
  Suspicious: "의심이 많은",
  Tactless: "눈치 없는",
  Temperamental: "변덕스러운",
  Timid: "소심한",
  Uncommunicative: "지나치게 말수가 적은",
  Uncooperative: "비협조적인",
  Unethical: "비윤리적인",
  Ungrateful: "고마워할 줄 모르는",
  Unintelligent: "우둔한",
  Vain: "허영심이 강한",
  Verbose: "지나치게 말이 많은",
  Violent: "폭력적인",
  Volatile: "다혈질인",
  "Weak-Willed": "의지박약인",
  Whiny: "불평이 많은",
  Withdrawn: "움츠러드는",
  Workaholic: "일중독인",
  Worrywart: "사서 걱정하는",
} as const;
