name: Code deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/private-key.pem
          chmod 600 ~/private-key.pem

      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh

      - name: Add known host
        run: |
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Create real.env file
        run: |
          echo "ML_API_KEY=${{ secrets.ML_API_KEY }}" > real.env

      - name: Copy project files to remote server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
        run: |
          scp -P $REMOTE_PORT -i ~/private-key.pem -o StrictHostKeyChecking=no -r ./* $REMOTE_USER@$REMOTE_HOST:$REMOTE_TARGET

      - name: Copy real.env file to remote server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
        run: |
          scp -P $REMOTE_PORT -i ~/private-key.pem -o StrictHostKeyChecking=no real.env $REMOTE_USER@$REMOTE_HOST:$REMOTE_TARGET/real.env
          echo "Copied .env file to remote server"

#      - name: Create logs directory on remote server
#        env:
#          REMOTE_USER: ${{ secrets.REMOTE_USER }}
#          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
#          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
#        run: |
#          ssh -i ~/private-key.pem -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "sudo mkdir -p $REMOTE_TARGET/logs/\$(date +\"%Y-%m\")"

      - name: Upload logging configuration to remote server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
        run: |
          scp -P $REMOTE_PORT -i ~/private-key.pem -o StrictHostKeyChecking=no logging_config.ini $REMOTE_USER@$REMOTE_HOST:$REMOTE_TARGET/logging_config.ini
          echo "Uploaded logging configuration to remote server"

      - name: Restart Uvicorn server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
        run: |
          ssh -i ~/private-key.pem -p $REMOTE_PORT $REMOTE_USER@$REMOTE_HOST "./start_uvicorn.sh"