name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/deploy_key.pem
          chmod 600 /tmp/deploy_key.pem
          eval "$(ssh-agent -s)"
          ssh-add /tmp/deploy_key.pem
          ssh-keyscan -p 57447 -H 14.35.173.14 >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          echo "ML_API_KEY=${{ secrets.ML_API_KEY }}" >> .env

      - name: Pull code on server and upload .env
        run: |
          scp -P 57447 -o StrictHostKeyChecking=no .env elicer@14.35.173.14:/path/to/your/project/.env
          ssh -p 57447 -o StrictHostKeyChecking=no elicer@14.35.173.14 "cd /path/to/your/project && git pull"
